MODEL:
  ROI_HEADS:
    NUM_CLASSES: 20
    SCORE_THRESH_TEST: 0.005
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 2000
  BASE_LR: 0.001
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
DATASETS:
  TRAIN: ()
  TEST: ()
VERSION: 2